services:
   - type: cron
     name: vital-tracker-cron
     region: ohio
     env: python
     plan: starter
     buildCommand: "./build.sh"
     startCommand: "poetry run vital-tracker"
     autoDeploy: true
     schedule: "*/10 * * * *"
     envVars:
       - fromGroup: vital-tracker